### ISSUE TITLE
I am getting an error with the make tb_toolchain command.  The tb_verilator command still works correctly.  (on M1 MacOS)

### ISSUE THREAD

**Issue by Kr1dhay** [EIE2-IAC-Labs/Lab0-devtools#1]
kridhaymahesh@Kridhays-MacBook toolchain % make tb_toolchain
==== Building Toolchain test =====
/bin/sh: riscv64-unknown-elf-gcc: command not found
make: *** [tb_toolchain] Error 127
kridhaymahesh@Kridhays-MacBook toolchain %

**Comment by Jpnock** [comment]
Hi @Kr1dhay 

Try adding the following to the top of the `Makefile` in the `toolchain` directory

https://github.com/EIE2-IAC-Labs/Lab0-devtools/blob/5043b459fd9b2407de1ed3e90c1699abffd68e58/autumn/workspace/toolchain/Makefile#L1

Let me know if that solves the problem.

---

I believe this problem is localised to Mac OS and may be because `Make` uses `sh` instead of your normal terminal to run commands. On Mac OS, I don't think the PATH is correctly configured for `sh`, only the normal terminal `zsh`.

If that doesn't work, show me the output of `ls /opt/riscv/bin` and `which riscv64-unknown-elf-gcc`. It should look as follows:

```
user@host:~$ ls /opt/riscv/bin
riscv64-unknown-elf-addr2line  riscv64-unknown-elf-c++filt  riscv64-unknown-elf-gcc         riscv64-unknown-elf-gcc-ranlib  riscv64-unknown-elf-gdb            riscv64-unknown-elf-ld.bfd    riscv64-unknown-elf-objdump  riscv64-unknown-elf-size
riscv64-unknown-elf-ar         riscv64-unknown-elf-cpp      riscv64-unknown-elf-gcc-12.2.0  riscv64-unknown-elf-gcov        riscv64-unknown-elf-gdb-add-index  riscv64-unknown-elf-lto-dump  riscv64-unknown-elf-ranlib   riscv64-unknown-elf-strings
riscv64-unknown-elf-as         riscv64-unknown-elf-elfedit  riscv64-unknown-elf-gcc-ar      riscv64-unknown-elf-gcov-dump   riscv64-unknown-elf-gprof          riscv64-unknown-elf-nm        riscv64-unknown-elf-readelf  riscv64-unknown-elf-strip
riscv64-unknown-elf-c++        riscv64-unknown-elf-g++      riscv64-unknown-elf-gcc-nm      riscv64-unknown-elf-gcov-tool   riscv64-unknown-elf-ld             riscv64-unknown-elf-objcopy   riscv64-unknown-elf-run

user@host:~$ which riscv64-unknown-elf-gcc
/opt/riscv/bin/riscv64-unknown-elf-gcc
```

**Comment by Kr1dhay** [comment]
Hi, thank you for the fix.  Unfortunately that didn't seem to fix the problem.  Here is a screenshot of the error message I received.
<img width="641" alt="Screenshot 2022-10-12 at 12 01 07" src="https://user-images.githubusercontent.com/78971881/195326547-de1f8e5a-47d4-4ef9-b7d5-63cdb853cf72.png">

**Comment by Jpnock** [comment]
> Hi, thank you for the fix. Unfortunately that didn't seem to fix the problem. Here is a screenshot of the error message I received. <img alt="Screenshot 2022-10-12 at 12 01 07" width="641" src="https://user-images.githubusercontent.com/78971881/195326547-de1f8e5a-47d4-4ef9-b7d5-63cdb853cf72.png">

What's your shortcode, I'll give you a call on teams

**Comment by Kr1dhay** [comment]
km1221

**Comment by Jpnock** [comment]
Solved: for some reason the darwin.sh script exited after gtkwave was installed. This meant that all of the instructions below it were not executed. Running the same instructions again worked fine.
